import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Roboto, Roboto_Mono } from "next/font/google";
import { Pixelify_Sans } from "next/font/google";
import NavIcon from "../components/NavIcon";
import { NavigationProvider } from "../contexts/NavigationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

const robotoMono = Roboto_Mono({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

const pixelifySans = Pixelify_Sans({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-pixelify-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${robotoMono.variable} ${pixelifySans.variable} antialiased`}
        style={{ background: "#EAEAEA" }}
      >
        <NavigationProvider>
          {/* Figma-inspired Header (refined) */}
          <header
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              padding: "0.5rem 1.5rem",
              background: "#242424",
              minHeight: 58,
              height: 64,
              boxSizing: "border-box",
              color: "#fff",
              fontFamily: "var(--font-roboto), Roboto, Arial, sans-serif",
              position: "relative",
              zIndex: 2
            }}
          >
            {/* Logo */}
            <div style={{ display: "flex", alignItems: "center", position: "absolute", left: 32, top: 0, bottom: 0, height: "100%" }}>
              <img src="/assets/logo.png" alt="Carnegie Mellon University Logo" style={{ height: 40, width: "auto" }} />
            </div>
            {/* Breadcrumbs */}
            <nav style={{ flex: 0, textAlign: "center" }}>
              <span style={{ fontWeight: 400, fontSize: "1rem", color: "#fff", letterSpacing: 0.1, fontFamily: "inherit" }}>
                User01/Dashboard/PipeReport1/DataMonitor
              </span>
            </nav>
            {/* Profile Icon */}
            <div style={{ display: "flex", alignItems: "center", position: "absolute", right: 32, top: 0, bottom: 0, height: "100%" }}>
              <span
                style={{
                  display: "inline-flex",
                  alignItems: "center",
                  justifyContent: "center",
                  width: 36,
                  height: 36,
                  borderRadius: "50%",
                  background: "#f3f4f6",
                  border: "1px solid #e5e7eb",
                  fontSize: 20,
                  color: "#555",
                }}
                title="Profile"
              >
                {/* Simple user icon (can be replaced with an SVG or image) */}
                <svg width="22" height="22" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 20c0-2.2 3.6-4 8-4s8 1.8 8 4"/></svg>
              </span>
            </div>
            {/* 2px line at the very bottom edge of the header */}
            <div style={{ position: "absolute", left: 0, bottom: 0, height: 2, width: "100%", background: "#484848", zIndex: 3 }} />
          </header>
          {/* Sidebar Navigation */}
          <aside
            style={{
              position: "fixed",
              top: 0,
              left: 0,
              width: 96,
              height: "100vh",
              background: "#242424",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              zIndex: 1,
              borderRight: "1px solid #222"
            }}
          >
            {/* Icons container, fills remaining space */}
            <div style={{ flex: 1, display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "flex-start", width: "100%", marginTop: 100 }}>
              {/* Icon 1: Job */}
              <NavIcon 
                iconName="job" 
                alt="Jobs"
              />
              {/* Icon 2: Map */}
              <NavIcon 
                iconName="map" 
                alt="Map"
              />
              {/* Icon 3: Bot */}
              <NavIcon 
                iconName="bot" 
                alt="Bot"
              />
            </div>
          </aside>
          {/* Main content */}
          <main>
            {children}
          </main>
        </NavigationProvider>
      </body>
    </html>
  );
}
